theme: jekyll-theme-minimal
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: ML-assisted Low Power sensing: Gyro-limited for Pose Estimation
description: Project for UCLA ECEM202A/CSM213A (Fall 2023)
