theme: jekyll-theme-minimal
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: ML Assisted Intermittent Gyroscope Utilization for Low-Power Sensing
logo: /media/orientation.jpg
description: Project for UCLA ECEM202A/CSM213A (Fall 2023)
